# Generated by Django 5.2.17 on 2026-08-26 07:43

import accounts.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be 7-20 digits, optionally prefixed with '+'.", regex='^\\+?[0-9]{7,20}$')])),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super administrator'), ('ADMIN', 'Organization administrator'), ('USER', 'User')], db_index=True, default='USER', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the Django admin site.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('organization', models.ForeignKey(blank=True, help_text='Null only for platform level SUPER_ADMIN accounts that operate the deployment itself.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizations.organization')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
                'ordering': ('name', 'email'),
                'indexes': [models.Index(fields=['organization', 'is_active'], name='user_org_active_idx'), models.Index(fields=['organization', 'role'], name='user_org_role_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('organization__isnull', False), ('role', 'SUPER_ADMIN'), _connector='OR'), name='user_requires_organization_unless_super_admin')],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
