"""Location serializers.

Note what the request serializer does *not* accept: any field describing
presence. The contract is "the client reports what the GPS said, the backend
decides what it means", and a payload that tries to assert a status is rejected
with an explicit error rather than silently ignored.
"""
from __future__ import annotations

from typing import Any

from rest_framework import serializers

from locations.models import LocationAnomaly, LocationUpdate
from locations.validators import reject_client_supplied_status


class LocationUpdateRequestSerializer(serializers.Serializer):
    """Incoming GPS observation."""

    latitude = serializers.FloatField(min_value=-90, max_value=90)
    longitude = serializers.FloatField(min_value=-180, max_value=180)
    accuracy = serializers.FloatField(min_value=0)
    recorded_at = serializers.DateTimeField(
        help_text="ISO 8601 device timestamp of the fix, with timezone (e.g. 2026-08-26T12:20:15Z)."
    )

    speed = serializers.FloatField(required=False, allow_null=True, min_value=0)
    heading = serializers.FloatField(required=False, allow_null=True, min_value=0, max_value=360)
    altitude = serializers.FloatField(required=False, allow_null=True)

    device_id = serializers.CharField(required=False, allow_blank=True, max_length=64)
    session_id = serializers.CharField(required=False, allow_blank=True, max_length=64)
    client_event_id = serializers.CharField(
        required=False,
        allow_blank=True,
        allow_null=True,
        max_length=64,
        help_text=(
            "Idempotency key generated by the PWA. Re-sending the same key after a "
            "network failure returns the original result instead of duplicating it."
        ),
    )

    def validate(self, attrs: dict[str, Any]) -> dict[str, Any]:
        reject_client_supplied_status(self.initial_data)
        return attrs


class AnomalySerializer(serializers.ModelSerializer):
    user_email = serializers.EmailField(source="user.email", read_only=True)
    user_name = serializers.CharField(source="user.name", read_only=True)

    class Meta:
        model = LocationAnomaly
        fields = (
            "id",
            "user",
            "user_email",
            "user_name",
            "location_update",
            "anomaly_type",
            "severity",
            "details",
            "created_at",
        )
        read_only_fields = fields


class LocationUpdateSerializer(serializers.ModelSerializer):
    """Stored fix, as returned by history endpoints."""

    anomalies = AnomalySerializer(many=True, read_only=True)
    delay_seconds = serializers.FloatField(read_only=True)

    class Meta:
        model = LocationUpdate
        fields = (
            "id",
            "user",
            "latitude",
            "longitude",
            "accuracy",
            "speed",
            "heading",
            "altitude",
            "recorded_at",
            "received_at",
            "delay_seconds",
            "device_id",
            "session_id",
            "client_event_id",
            "confidence",
            "is_trusted",
            "is_flagged",
            "anomalies",
        )
        read_only_fields = fields


class PresenceOutcomeSerializer(serializers.Serializer):
    """What one location update did to one presence row."""

    geofence_id = serializers.IntegerField()
    geofence_name = serializers.CharField()
    status = serializers.CharField()
    previous_status = serializers.CharField()
    changed = serializers.BooleanField()
    events = serializers.ListField(child=serializers.CharField())
    verdict = serializers.CharField()
    confidence = serializers.CharField()
    distance_to_boundary_m = serializers.FloatField()
    accuracy_margin_m = serializers.FloatField()
    consecutive_inside = serializers.IntegerField()
    consecutive_outside = serializers.IntegerField()
    required_inside_readings = serializers.IntegerField()
    required_outside_readings = serializers.IntegerField()
    check_in_at = serializers.DateTimeField(allow_null=True)
    check_out_at = serializers.DateTimeField(allow_null=True)
    last_seen_at = serializers.DateTimeField(allow_null=True)


class LocationUpdateResponseSerializer(serializers.Serializer):
    """Documentation schema for POST /api/location/update/."""

    location_update_id = serializers.IntegerField()
    duplicate = serializers.BooleanField()
    trusted = serializers.BooleanField()
    recorded_at = serializers.DateTimeField()
    received_at = serializers.DateTimeField()
    effective_status = serializers.CharField()
    presence = PresenceOutcomeSerializer(many=True)
    anomalies = serializers.ListField(child=serializers.DictField())
    next_ping_seconds = serializers.IntegerField()


class LastLocationSerializer(serializers.Serializer):
    latitude = serializers.FloatField()
    longitude = serializers.FloatField()
    accuracy = serializers.FloatField()
    recorded_at = serializers.DateTimeField()
    received_at = serializers.DateTimeField()
    confidence = serializers.CharField()
    is_trusted = serializers.BooleanField()


class ClientConfigSerializer(serializers.Serializer):
    """Tuning the PWA must honour instead of hard-coding it."""

    recommended_ping_interval_seconds = serializers.IntegerField()
    max_acceptable_accuracy_m = serializers.FloatField()
    stale_after_seconds = serializers.IntegerField()
    max_location_age_seconds = serializers.IntegerField()


class LocationStatusResponseSerializer(serializers.Serializer):
    """Documentation schema for GET /api/location/status/."""

    date = serializers.DateField()
    effective_status = serializers.CharField()
    geofence_id = serializers.IntegerField(allow_null=True)
    geofence_name = serializers.CharField(allow_null=True)
    check_in_at = serializers.DateTimeField(allow_null=True)
    check_out_at = serializers.DateTimeField(allow_null=True)
    last_seen_at = serializers.DateTimeField(allow_null=True)
    last_location = LastLocationSerializer(allow_null=True)
    client_config = ClientConfigSerializer()
