# Generated by Django 5.2.17 on 2026-08-26 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('code', models.CharField(help_text='Short stable identifier used by integrations, e.g. SITARE.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Code must be 2-32 characters of uppercase letters, digits, hyphen or underscore, and must not start with a separator.', regex='^[A-Z0-9][A-Z0-9_-]{1,31}$')])),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone used to decide which calendar day an attendance record belongs to.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations_organization',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active'], name='org_is_active_idx')],
            },
        ),
    ]
