# Generated by Django 5.2.17 on 2026-08-26 07:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('accuracy', models.FloatField(help_text='Radius of 68% confidence in metres, as reported by the browser.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('speed', models.FloatField(blank=True, help_text='Metres per second.', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Degrees clockwise from true north.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(360.0)])),
                ('altitude', models.FloatField(blank=True, help_text='Metres above WGS84.', null=True)),
                ('recorded_at', models.DateTimeField(help_text='Device clock time of the fix.')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='Server time the fix was accepted.')),
                ('device_id', models.CharField(blank=True, default='', max_length=64)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('client_event_id', models.CharField(blank=True, help_text='Client generated idempotency key. Re-POSTing the same key returns the original result instead of creating a duplicate.', max_length=64, null=True)),
                ('confidence', models.CharField(choices=[('HIGH', 'Accuracy within the acceptable threshold'), ('LOW', 'Accuracy worse than the acceptable threshold')], default='HIGH', help_text='HIGH when accuracy is within MAX_ACCEPTABLE_ACCURACY_M.', max_length=8)),
                ('is_trusted', models.BooleanField(default=True, help_text='False when a HIGH severity anomaly was detected. Untrusted fixes are stored for the audit trail but never drive presence transitions.')),
                ('is_flagged', models.BooleanField(default=False, help_text='At least one anomaly was recorded for this fix.')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'locations_locationupdate',
                'ordering': ('-recorded_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LocationAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('IMPOSSIBLE_SPEED', 'Implied speed exceeds the plausible maximum'), ('COORDINATE_JUMP', 'Large positional jump in a short window'), ('FUTURE_TIMESTAMP', 'recorded_at is in the future'), ('STATIONARY_REPEAT', 'Identical coordinates repeated for a long period'), ('POOR_ACCURACY', 'Accuracy worse than the acceptable threshold'), ('HIGH_FREQUENCY', 'Update rate above the expected maximum'), ('STALE_READING', 'Fix is old but still within the accepted window')], max_length=32)),
                ('severity', models.CharField(choices=[('LOW', 'Informational'), ('MEDIUM', 'Worth reviewing'), ('HIGH', 'Reading excluded from presence decisions')], default='LOW', max_length=8)),
                ('details', models.JSONField(default=dict, help_text='Structured evidence, e.g. computed speed and window.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_anomalies', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_anomalies', to=settings.AUTH_USER_MODEL)),
                ('location_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='locations.locationupdate')),
            ],
            options={
                'db_table': 'locations_locationanomaly',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='locationupdate',
            index=models.Index(fields=['user', '-recorded_at'], name='locupd_user_recorded_idx'),
        ),
        migrations.AddIndex(
            model_name='locationupdate',
            index=models.Index(fields=['organization', '-recorded_at'], name='locupd_org_recorded_idx'),
        ),
        migrations.AddIndex(
            model_name='locationupdate',
            index=models.Index(fields=['-received_at'], name='locupd_received_idx'),
        ),
        migrations.AddIndex(
            model_name='locationupdate',
            index=models.Index(fields=['organization', 'is_flagged'], name='locupd_org_flagged_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationupdate',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', False)), fields=('user', 'client_event_id'), name='location_unique_client_event_per_user'),
        ),
        migrations.AddIndex(
            model_name='locationanomaly',
            index=models.Index(fields=['user', '-created_at'], name='anomaly_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='locationanomaly',
            index=models.Index(fields=['organization', 'anomaly_type'], name='anomaly_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='locationanomaly',
            index=models.Index(fields=['severity'], name='anomaly_severity_idx'),
        ),
    ]
