# Generated by Django 5.2.17 on 2026-08-26 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geofences', '0001_initial'),
        ('locations', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text="Attendance day in the organization's timezone, derived from recorded_at.")),
                ('status', models.CharField(choices=[('UNKNOWN', 'No usable information yet'), ('OUTSIDE', 'Confidently outside the area'), ('PRESENT', 'Confidently inside the area'), ('GONE', 'Was present and then confidently left'), ('STALE', 'Was present, then updates stopped arriving')], default='UNKNOWN', max_length=16)),
                ('check_in_at', models.DateTimeField(blank=True, help_text='First ENTERED of the day (device time).', null=True)),
                ('check_out_at', models.DateTimeField(blank=True, help_text='Most recent EXITED of the day (device time).', null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='recorded_at of the most recent trusted fix that reached this row.', null=True)),
                ('stale_since', models.DateTimeField(blank=True, help_text='Server time the row was marked STALE.', null=True)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('last_accuracy', models.FloatField(blank=True, null=True)),
                ('last_distance_m', models.FloatField(blank=True, help_text='Signed distance to the boundary at the last reading; negative inside.', null=True)),
                ('last_verdict', models.CharField(blank=True, choices=[('INSIDE', 'Confidently inside the entry boundary'), ('OUTSIDE', 'Confidently outside the exit boundary'), ('UNCERTAIN', 'Inside the hysteresis band or too imprecise to decide')], default='', max_length=16)),
                ('last_reading_at', models.DateTimeField(blank=True, help_text='Device time of the last reading applied to this row. Used to reject out-of-order deliveries and to reset stale streaks.', null=True)),
                ('consecutive_inside', models.PositiveSmallIntegerField(default=0)),
                ('consecutive_outside', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='geofences.geofence')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presence_presence',
                'ordering': ('-date', 'user_id'),
            },
        ),
        migrations.CreateModel(
            name='PresenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENTERED', 'Checked in'), ('EXITED', 'Checked out'), ('STALE', 'Updates stopped arriving'), ('LOCATION_RESTORED', 'Updates resumed after a gap')], max_length=24)),
                ('reason', models.CharField(blank=True, choices=[('CONSECUTIVE_INSIDE', 'Required inside readings reached'), ('CONSECUTIVE_OUTSIDE', 'Required outside readings reached'), ('UPDATES_TIMED_OUT', 'No update within the stale timeout'), ('UPDATES_RESUMED', 'A trusted update arrived after a timeout'), ('DAY_ROLLOVER', 'Attendance day ended while still checked in')], default='', max_length=24)),
                ('previous_status', models.CharField(blank=True, choices=[('UNKNOWN', 'No usable information yet'), ('OUTSIDE', 'Confidently outside the area'), ('PRESENT', 'Confidently inside the area'), ('GONE', 'Was present and then confidently left'), ('STALE', 'Was present, then updates stopped arriving')], default='', max_length=16)),
                ('new_status', models.CharField(blank=True, choices=[('UNKNOWN', 'No usable information yet'), ('OUTSIDE', 'Confidently outside the area'), ('PRESENT', 'Confidently inside the area'), ('GONE', 'Was present and then confidently left'), ('STALE', 'Was present, then updates stopped arriving')], default='', max_length=16)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(help_text='When the transition happened: device time for reading-driven events, server time for timeout-driven events.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presence_events', to='geofences.geofence')),
                ('location_update', models.ForeignKey(blank=True, help_text='The fix that triggered the transition, when there was one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_events', to='locations.locationupdate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_events', to='organizations.organization')),
                ('presence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='presence.presence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'presence_presenceevent',
                'ordering': ('-timestamp', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['organization', 'date', 'status'], name='presence_org_day_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['user', '-date'], name='presence_user_day_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['status', 'last_seen_at'], name='presence_status_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['geofence', 'date'], name='presence_geofence_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.UniqueConstraint(fields=('user', 'geofence', 'date'), name='presence_unique_user_geofence_day'),
        ),
        migrations.AddIndex(
            model_name='presenceevent',
            index=models.Index(fields=['user', '-timestamp'], name='event_user_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='presenceevent',
            index=models.Index(fields=['organization', '-timestamp'], name='event_org_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='presenceevent',
            index=models.Index(fields=['geofence', 'event_type'], name='event_geofence_type_idx'),
        ),
        migrations.AddIndex(
            model_name='presenceevent',
            index=models.Index(fields=['event_type', '-timestamp'], name='event_type_ts_idx'),
        ),
        migrations.AddConstraint(
            model_name='presenceevent',
            constraint=models.UniqueConstraint(fields=('presence', 'event_type', 'timestamp'), name='presence_event_unique_transition'),
        ),
    ]
